### ISSUE TITLE
Confusion at MetaCPAN

### ISSUE THREAD

**Issue by openstrike** [neilb/Mail-Sendmail#6]
If one were to search at MetaCPAN for Mail::Sendmail one would see that [the top result is actually for Test::Smoke](https://metacpan.org/search?q=mail%3A%3Asendmail). If you then try to follow the link to the real dist listed under NEILB (the second result) it takes you to https://metacpan.org/pod/Mail::Sendmail which again is inside the Test::Smoke dist.

I suspect that this is probably not a problem with the Mail::Sendmail dist and should either be corrected in Test::Smoke or MetaCPAN itself but wanted to raise it here in case you understood the issue better than I do.

**Comment by neilb** [comment]
Good catch!

I've raised this on the #metacpan channel on IRC. Mail::Sendmail is being bundled with Test-Smoke, but the dist's metadata says that the inc/ directory (where it's bundled) shouldn't be indexed. So I think it's a MetaCPAN issue.

I'll leave this open until either I raise a ticket on MetaCPAN, or I learn that it's something else :-)

Cheers!

**Comment by neilb** [comment]
Issue on MetaCPAN: https://github.com/metacpan/metacpan-api/issues/811

**Comment by openstrike** [comment]
FYI, this appears to be fixed now.
